version: '3.8'

networks:
  public:
    driver: bridge
  internal:
    driver: bridge
    internal: true

services:
  api-gateway:
    image: api-gateway:latest
    container_name: iwa-api-gateway
    build:
      context: .
      dockerfile: ./api-gateway/Dockerfile
    networks:
      - public
      - internal
    environment:
      - SERVICES_AUTH_URL=http://iwa-auth-service:8082
      - SERVICES_USER_URL=http://iwa-user-service:8081
      - SERVICES_KEYCLOAK_URL=http://iwa-keycloak:8080
    ports:
      - "8080:8080"
    depends_on:
      - auth-service
      - user-service
      - keycloak

  auth-service:
    image: auth-service:latest
    container_name: iwa-auth-service
    build:
      context: .
      dockerfile: ./auth-service/Dockerfile
    networks:
      - internal
    environment:
      - SERVER_ADDRESS=0.0.0.0
      - KEYCLOAK_AUTH_SERVER_URL=http://iwa-keycloak:8080
      - KEYCLOAK_REALM=IWA_NextLevel
    expose:
      - "8082"
    depends_on:
      - keycloak
      - postgres

  user-service:
    image: user-microservice:latest
    container_name: iwa-user-service
    build:
      context: .
      dockerfile: ./user-microservice/Dockerfile
    networks:
      - internal
    environment:
      - SERVER_ADDRESS=0.0.0.0
      - DATABASE_URL=jdbc:postgresql://iwa-user-postgres:5432/iwa_users
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
      - KEYCLOAK_ISSUER_URI=http://iwa-keycloak:8080/realms/IWA_NextLevel
      - KEYCLOAK_JWK_SET_URI=http://iwa-keycloak:8080/realms/IWA_NextLevel/protocol/openid-connect/certs
    expose:
      - "8081"
    depends_on:
      - postgres
      - keycloak

  keycloak:
    image: quay.io/keycloak/keycloak:26.0.7
    container_name: iwa-keycloak
    command: start-dev --import-realm
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTP_PORT: 8080
      KC_HOSTNAME_URL: http://localhost:8080
      KC_HOSTNAME_ADMIN_URL: http://localhost:9090
      KC_HOSTNAME_STRICT: "false"
      KC_HOSTNAME_STRICT_BACKCHANNEL: "false"
      KC_HTTP_RELATIVE_PATH: /
    networks:
      - public
      - internal
    expose:
      - "8080"
    ports:
      - "9090:8080"
    volumes:
      - ../keycloak-config:/opt/keycloak/data/import:ro
      - ./keycloak-webhook-extension/target/keycloak-webhook-extension-1.0.0.jar:/opt/keycloak/providers/keycloak-webhook-extension-1.0.0.jar:ro
    depends_on:
      - postgres

  postgres:
    image: postgres:16-alpine
    container_name: iwa-user-postgres
    environment:
      POSTGRES_DB: iwa_users
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - internal
    expose:
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
